# Generated by Django 6.0.2 on 2026-02-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_healthprofile_ai_signature_healthprofile_ai_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], max_length=1),
        ),
    ]
