# Generated by Django 6.0.2 on 2026-02-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_healthprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='exercise_frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='exercise_time_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
