# Generated by Django 6.0.2 on 2026-02-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_healthprofile_exercise_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='sleep_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
