# Generated by Django 6.0.2 on 2026-02-19 12:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('NEWS', 'News'), ('PAPER', 'Paper')], max_length=10)),
                ('title', models.CharField(max_length=400)),
                ('summary', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('normalized_url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('region', models.CharField(blank=True, max_length=32)),
                ('authors', models.JSONField(blank=True, default=list)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=200)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DigestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('score', models.FloatField(default=0.0)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='news.digest')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.item')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('RSS', 'RSS/Atom'), ('API', 'Official API')], max_length=8)),
                ('url_or_endpoint', models.URLField()),
                ('language', models.CharField(blank=True, max_length=16)),
                ('region', models.CharField(blank=True, max_length=32)),
                ('weight', models.FloatField(default=1.0)),
                ('enabled', models.BooleanField(default=True)),
                ('etag', models.CharField(blank=True, max_length=200)),
                ('last_modified', models.CharField(blank=True, max_length=200)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, to='news.category')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='news.source'),
        ),
        migrations.CreateModel(
            name='UserItemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_later', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=16)),
                ('region', models.CharField(blank=True, max_length=32)),
                ('include_keywords', models.TextField(blank=True)),
                ('exclude_keywords', models.TextField(blank=True)),
                ('daily_limit', models.IntegerField(default=20)),
                ('push_time', models.TimeField(default=datetime.time(8, 0))),
                ('include_academic', models.BooleanField(default=False)),
                ('last_digest_date', models.DateField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, to='news.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='digest',
            index=models.Index(fields=['user', 'date'], name='news_digest_user_id_ca084f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='digest',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='digestentry',
            index=models.Index(fields=['digest', 'rank'], name='news_digest_digest__3de669_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='digestentry',
            unique_together={('digest', 'item')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['source', 'published_at'], name='news_item_source__88916b_idx'),
        ),
        migrations.AddIndex(
            model_name='useritemstate',
            index=models.Index(fields=['user', 'updated_at'], name='news_userit_user_id_6b4c96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useritemstate',
            unique_together={('user', 'item')},
        ),
    ]
