# Generated by Django 6.0.2 on 2026-02-20 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(max_length=1000)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('rss_summary', models.TextField(blank=True, default='')),
                ('content_text', models.TextField(blank=True, default='')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('ai_summaries', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('rss_url', models.URLField(unique=True)),
                ('language', models.CharField(default='zh', max_length=10)),
                ('region', models.CharField(blank=True, default='', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('weight', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DailyBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('language', models.CharField(default='zh', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_briefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'unique_together': {('user', 'date', 'language')},
            },
        ),
        migrations.CreateModel(
            name='BriefEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('url', models.URLField(max_length=1000)),
                ('source_name', models.CharField(max_length=120)),
                ('score', models.FloatField(default=0)),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='news.dailybrief')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newsitem')),
            ],
            options={
                'ordering': ['-score', '-item__published_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='newsitem',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='news.newssource'),
        ),
        migrations.AddField(
            model_name='newssource',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='sources', to='news.topic'),
        ),
        migrations.CreateModel(
            name='UserNewsPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('language', models.CharField(default='zh', max_length=10)),
                ('region', models.CharField(blank=True, default='', max_length=10)),
                ('keywords', models.CharField(blank=True, default='', max_length=300)),
                ('max_items', models.PositiveSmallIntegerField(default=8)),
                ('topics', models.ManyToManyField(blank=True, to='news.topic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='news_pref', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='newsitem',
            index=models.Index(fields=['published_at'], name='news_newsit_publish_9ada03_idx'),
        ),
        migrations.AddIndex(
            model_name='newsitem',
            index=models.Index(fields=['fetched_at'], name='news_newsit_fetched_16dceb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='newsitem',
            unique_together={('source', 'guid')},
        ),
    ]
