# Generated by Django 6.0.2 on 2026-02-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_create_newssource_topics_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='item_type',
            field=models.CharField(choices=[('RSS', 'RSS/Atom'), ('API', 'Official API')], default='RSS', max_length=8),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usernewspreference',
            name='include_keywords',
            field=models.CharField(default='', max_length=255),
        ),
    ]
