# Generated by Django 6.0.2 on 2026-02-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsitem_item_type_newsitem_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernewspreference',
            name='topics',
            field=models.ManyToManyField(blank=True, default='', to='news.topic'),
        ),
    ]
