# Generated by Django 6.0.2 on 2026-02-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_usernewspreference_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='language',
            field=models.CharField(default='zh', max_length=100),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='name',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='region',
            field=models.CharField(blank=True, default='CN', max_length=100),
        ),
    ]
