# Generated by Django 4.2.29 on 2026-03-27 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, default='', max_length=50, verbose_name='昵称')),
                ('signature', models.CharField(blank=True, default='', max_length=120, verbose_name='个性签名')),
                ('bio', models.TextField(blank=True, default='', verbose_name='个人简介')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='手机号')),
                ('location', models.CharField(blank=True, default='', max_length=100, verbose_name='所在地')),
                ('website', models.URLField(blank=True, default='', verbose_name='个人网站')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
